djangoapp/avaliacoes/urls.py
from django.urls import path
from avaliacoes import views

app_name = 'avaliacoes'

urlpatterns = [
    path('adicionar/<int:campo_id>/', views.adicionar_avaliacao, name='adicionar_avaliacao'),
]

djangoapp/blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from blog.views import index

app_name = 'blog'

urlpatterns = [
    path('', index, name='index'),
]

djangoapp/campos/urls.py
from django.urls import path
from campos.views import list_fields, detail_fields, map_view

app_name = 'campos'

urlpatterns = [
    path('', list_fields, name='list_fields'),
    path('campo/<int:pk>/',detail_fields, name='detail_fields'),
    path('mapa/', map_view, name='map_view'),

]

djangoapp/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('mfa/', include('allauth.mfa.urls')),
    path('' , include('usuarios.urls')),
    path('campos/', include('campos.urls')),
    path('reservas/', include('reservas.urls')),
    path('avaliacoes/', include('avaliacoes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

djangoapp/reservas/urls.py
from django.urls import path
from . import views

app_name = 'reservas'

urlpatterns = [
    path('reservar/<int:campo_id>/', views.reservar, name='reservar'),
    path('confirmar/', views.confirmar_reserva, name='confirmar_reserva'),
    path('historico/', views.historico_reservas, name='historico_reservas'),
    path('cancelar/<int:reserva_id>/', views.cancelar_reserva, name='cancelar_reserva'),

]

djangoapp/usuarios/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from usuarios.views import index
from .views import profile_view

app_name = 'usuarios'

urlpatterns = [
    path('', index, name='index'),
    path('profile/', profile_view, name='profile'),

]

djangoapp/campos/models.py
from django.db import models

class Campo(models.Model):
    GRAMADO_CHOICES = [
        ('natural', 'Natural'),
        ('sintetico', 'Sintético'),
    ]

    nome = models.CharField(max_length=100)
    cidade = models.CharField(max_length=100)
    endereco = models.CharField(max_length=255)
    dimensao = models.CharField(max_length=50)
    preco_por_hora = models.DecimalField(max_digits=6, decimal_places=2)
    tipo_gramado = models.CharField(max_length=10, choices=GRAMADO_CHOICES)
    iluminacao_noturna = models.BooleanField(default=False)
    vestiarios = models.BooleanField(default=False)
    foto = models.ImageField(upload_to='fotos_campos/', null=True, blank=True)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    

    def __str__(self):
        return self.nome

djangoapp/reservas/models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError
from campos.models import *

class Reserva(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    campo = models.ForeignKey(Campo, on_delete=models.CASCADE)
    data_inicio = models.DateTimeField()
    data_fim = models.DateTimeField()
    preco_total = models.DecimalField(max_digits=10, decimal_places=2)
    criado_em = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    def __str__(self):
        return f"Reserva de {self.usuario} no campo {self.campo} de {self.data_inicio} até {self.data_fim}"

    def clean(self):
        # Verificar se existe conflito de horário
        conflitos = Reserva.objects.filter(
            campo=self.campo,
            data_inicio__lt=self.data_fim,
            data_fim__gt=self.data_inicio,
            is_active=True
        ).exclude(id=self.pk)
        
        if conflitos.exists():
            raise ValidationError("Este horário já está reservado ou bloqueado!")

    def save(self, *args, **kwargs):
        self.clean()  # Verifica a disponibilidade antes de salvar
        super().save(*args, **kwargs)

djangoapp/campos/forms.py
from django import forms

class CampoSearchForm(forms.Form):
    cidade = forms.CharField(required=False, label='Cidade')
    tipo_gramado = forms.ChoiceField(
        choices=[('sintetico', 'sintetico'), ('natural', 'natural')],
        required=False,
        label='Tipo de Gramado'
    )
    iluminacao_noturna = forms.ChoiceField(
        choices=[('', ''), ('false', '0'), ('true', '1')],
        required=False,
        label='iluminacao_noturna'
    )
    vestiarios = forms.ChoiceField(
        choices=[('', ''), ('false', '0'), ('true', '1')],
        required=False,
        label='vestiarios'
        )

djangoapp/campos/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Campo
from avaliacoes.models import Avaliacao
from reservas.views import Reserva
from django.conf import settings
from .forms import CampoSearchForm
from django.utils import timezone
import json
import requests

def list_fields(request):
    form = CampoSearchForm(request.GET or None)
    campos = Campo.objects.all()


    print(form.errors)
    if form.is_valid():
        cidade = form.cleaned_data.get('cidade')
        tipo_gramado = form.cleaned_data.get('tipo_gramado')
        iluminacao_noturna = form.cleaned_data['iluminacao_noturna']
        vestiarios = form.cleaned_data.get('vestiarios')

        if cidade:
            campos = campos.filter(cidade__icontains=cidade)
        if tipo_gramado:
            campos = campos.filter(tipo_gramado=tipo_gramado)
        if iluminacao_noturna == 'true':
            campos = campos.exclude(iluminacao_noturna=False)
        if iluminacao_noturna == 'false':
            campos = campos.filter(iluminacao_noturna=False)
        if vestiarios == 'true':
            campos = campos.exclude(iluminacao_noturna=False)
        if vestiarios == 'false':
            campos = campos.filter(iluminacao_noturna=False)

    print(form.cleaned_data)
    return render(request, 'usuarios/index.html', {'campos': campos, 'form': form})

def geocode_address(cidade, endereco):
    api_key = 'AIzaSyCnyOD_c4KKH7mSvQP_3QObDjg5cyawnC8'
    
    def fetch_geocode(url):
        try:
            response = requests.get(url)
            response.raise_for_status()  # Levanta um erro para códigos de status HTTP 4xx/5xx
            return response.json()
        except requests.RequestException as e:
            print(f"Erro ao fazer requisição: {e}")
            return None

    # Construindo a URL de geocodificação principal
    geocode_url = f"https://maps.googleapis.com/maps/api/geocode/json?address={endereco},{cidade}&key={api_key}"
    
    # Realiza a requisição para a URL principal
    geocode_data = fetch_geocode(geocode_url)

    if geocode_data and geocode_data['status'] == 'OK' and geocode_data['results']:
        location = geocode_data['results'][0]['geometry']['location']
        return location['lat'], location['lng']
    else:
        # Tentativa de fallback, adicionando a cidade ao endereço
        endereco_com_cidade = f"{cidade},{endereco}"
        fallback_geocode_url = f"https://maps.googleapis.com/maps/api/geocode/json?address={endereco_com_cidade}&key={api_key}"
        
        # Realiza a requisição para a URL de fallback
        fallback_data = fetch_geocode(fallback_geocode_url)
        
        if fallback_data and fallback_data['status'] == 'OK' and fallback_data['results']:
            location = fallback_data['results'][0]['geometry']['location']
            return location['lat'], location['lng']
        
        # Coordenadas padrão em caso de falha
        print("Geocodificação falhou, retornando coordenadas padrão.")
        return None, None  # Coordenadas padrão (Brasília)


@login_required
def detail_fields(request, pk):
    campo = get_object_or_404(Campo, pk=pk)
    reservas = Reserva.objects.filter(usuario=request.user, campo=campo, is_active=True)
    now = timezone.now()
    avaliacao_existente = Avaliacao.objects.filter(campo=campo, usuario=request.user).exists()
    avaliacoes_ativas = Avaliacao.objects.filter(campo=campo, is_active=True)

    show_button = False
    for reserva in reservas:
        if reserva.data_fim < now:
            show_button = True
            break 
    
    # Realiza a geocodificação se latitude e longitude ainda não estiverem definidas
    if not campo.latitude or not campo.longitude:
        lat, lon = geocode_address(campo.endereco, campo.cidade)
        if lat and lon:
            campo.latitude = lat
            campo.longitude = lon
            campo.save()  # Salva as coordenadas no banco de dados
    latitude_str = f"{campo.latitude:.6f}" if campo.latitude else None
    longitude_str = f"{campo.longitude:.6f}" if campo.longitude else None

    return render(request, 'campo_detail.html', {
        'campo': campo,
        'latitude': latitude_str,
        'longitude': longitude_str,
        'reservas' : reservas,
        'now' : now,
        'avaliacao_existente' : avaliacao_existente,
        'avaliacoes': avaliacoes_ativas,
        'show_button' : show_button,

    })

def map_view(request):
    campos = list(Campo.objects.values('id','nome', 'endereco', 'latitude', 'longitude'))
    campos_json = json.dumps(campos)
    return render(request, 'map_view.html', {'campos_json': campos_json})

djangoapp/campos/templates/campo_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalhes do Campo</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">
            <i class="fa-solid fa-futbol"></i>
            Alugol
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'usuarios:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'usuarios:profile' %}">Perfil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">Campos</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container mt-5">
        <div class="row">
            <!-- Imagem e Informações do Campo -->
            <div class="col-md-7">
                <div class="card shadow-sm h-100">
                    {% if campo.foto %}
                    <img src="{{ campo.foto.url }}" class="card-img-top" alt="{{ campo.nome }}">
                    {% else %}
                    <img src="default-field.jpg" class="card-img-top" alt="Imagem padrão do campo">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ campo.nome }}</h5>
                        <p class="card-text"><strong>Localização:</strong> {{ campo.endereco }}</p>
                        <p class="card-text"><strong>Dimensão:</strong> {{ campo.dimensao }}</p>
                        <p class="card-text"><strong>Tipo de Gramado:</strong> {{ campo.get_tipo_gramado_display }}</p>
                        <p class="card-text"><strong>Iluminação Noturna:</strong> {% if campo.iluminacao_noturna %} Sim {% else %} Não {% endif %}</p>
                        <p class="card-text"><strong>Vestiário:</strong> {% if campo.vestiarios %} Sim {% else %} Não {% endif %}</p>
                        <p class="card-text"><strong>Preço:</strong> R$ {{ campo.preco_por_hora }}</p>
                    </div>
                </div>
            </div>

            <!-- Mapa -->
            <div class="col-md-5 h-50">
                <h5 class="card-title">Localização</h5>
                <div class="card mb-4 shadow-sm">
                    <div class="card-body" >
                        <div id="map" class="w-100" style="height: 400px;"></div>
                    </div>
                </div>

                <!-- Modal para Exibição de Erros -->
                <div class="modal fade" id="erroModal" tabindex="-1" aria-labelledby="erroModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="erroModalLabel">Erro na Reserva</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <p id="erroMensagem"></p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                            </div>
                        </div>
                    </div>
                </div>
                        <!-- Formulário de Reserva -->
        <div class="row mt-4 ">
            <div class="col-md-12 text-center">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h5 class="card-title text-center mb-4">Faça sua Reserva</h5>
                        <form method="POST" action="{% url 'reservas:reservar' campo.id %}">
                            {% csrf_token %}
                            <div class="form-group w-50 mx-auto">
                                <label for="id_data_inicio">Data e Hora de Início</label>
                                <input type="text" id="id_data_inicio" name="data_inicio" class="form-control shadow-sm text-center" required>                            </div>

                            <div class="form-group w-50 mx-auto ">
                                <label for="id_data_fim">Data e Hora de Fim</label>
                                <input type="text" id="id_data_fim" name="data_fim" class="form-control shadow-sm text-center" required>                            </div>
                                <div id="preco" class="mb-3 text-center">
                                    <p class="h5">Preço: R$ <span id="preco_valor">0</span></p>
                                    <input type="hidden" id="preco_total" name="preco_total" value="{{ preco_total }}">
                                </div>
                            <button type="submit" class="btn btn-primary">Confirmar Reserva</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
            </div>
        </div>


        <!-- Seção de Comentários ou Avaliações -->
        <div class="row mt-4 mb-4">
            <div class="col-md-12">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <!-- Exibir avaliações -->
                        <h3>Avaliações</h3>
                        <p>Número de Comentários: {{ avaliacoes.count }}</p>
        
                        <!-- Expandir avaliações -->
                        <div class="text-center mb-3">
                            <a class="btn btn-primary btn-sm " data-toggle="collapse" href="#avaliacoesCollapse" role="button" aria-expanded="false" aria-controls="avaliacoesCollapse">
                                <i class="fas fa-chevron-down"></i> Ver avaliações
                            </a>
                        </div>
                        <div class="collapse" id="avaliacoesCollapse">
                            <div class="card card-body">
                                {% for avaliacao in avaliacoes %}
                                    <div class="media mb-4">
                                        <img src="{{ avaliacao.usuario.userprofile.get_profile_picture_url }}" class="mr-3 rounded-circle" style="width: 60px; height: 60px;">
                                        <div class="media-body">
                                            <div class="d-flex justify-content-between align-items-center">
                                                <h5 class="mt-0">{{ avaliacao.usuario.username }}</h5>
                                                <div class="text-warning">
                                                    {% for i in "12345" %}
                                                        {% if i|add:"0"|slice:"0" <= avaliacao.estrelas %}
                                                            <i class="fas fa-star fa-lg"></i>
                                                        {% else %}
                                                            <i class="far fa-star fa-lg"></i>
                                                        {% endif %}
                                                    {% endfor %}
                                                </div>
                                            </div>
                                            <p class="text-muted mb-2">{{ avaliacao.data_criacao|date:"d/m/Y H:i" }}</p>
                                            <p>{{ avaliacao.comentario }}</p>
                                        </div>
                                    </div>
                                    <hr>
                                {% empty %}
                                    <p class="text-center">Sem avaliações ainda.</p>
                                {% endfor %}
                            </div>
                        </div>
        
                        {% if not avaliacao_existente %}
                            {% if show_button %}
                                <div class="card card-body mt-4">
                                    <h5 class="card-title">Adicionar uma avaliação?</h5>
                                    <p>Você só poderá fazer isso uma vez.</p>
                                    <a href="{% url 'avaliacoes:adicionar_avaliacao' campo.id %}" class="btn btn-primary">Adicionar Avaliação</a>
                                </div>
                            {% endif %}
                        {% else %}
                            <div class="alert alert-warning mt-4" role="alert">
                                Você já avaliou este campo.
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        
        
        
        
        
    <!-- Adicionando o Bootstrap, Leaflet e Flatpickr -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/pt.js"></script>
    

    <script>
    document.addEventListener('DOMContentLoaded', function () {
        // Inicializa o mapa com coordenadas fornecidas pela view Django
        var lat = parseFloat('{{ latitude|default:"-15.7801" }}');
        var lon = parseFloat('{{ longitude|default:"-47.9292" }}');
        var campoNome = "{{ campo.nome|escapejs }}";
        console.log('Latitude:', lat);
        console.log('Latitude:', lon);

        function initializeMap(lat, lon) {
            var map = L.map('map').setView([lat, lon], 15);
            L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                attribution: '© OpenStreetMap contributors'
            }).addTo(map);
            L.marker([lat, lon]).addTo(map)
                .bindPopup(campoNome)
                .openPopup();
        }

        initializeMap(lat, lon);

        // Inicializa o Flatpickr
        flatpickr("#id_data_inicio", {
            enableTime: true,
            dateFormat: "Y-m-d H:i",
            time_24hr: true
        });
        flatpickr("#id_data_fim", {
            enableTime: true,
            dateFormat: "Y-m-d H:i",
            time_24hr: true
        });

        // Calcula o preço com base na seleção
        document.querySelector('#id_data_inicio').addEventListener('change', updatePrice);
        document.querySelector('#id_data_fim').addEventListener('change', updatePrice);

        function updatePrice() {
            var dataInicio = flatpickr.parseDate(document.querySelector('#id_data_inicio').value, "Y-m-d H:i");
            var dataFim = flatpickr.parseDate(document.querySelector('#id_data_fim').value, "Y-m-d H:i");

            if (dataInicio && dataFim && dataInicio < dataFim) {
                var diffMs = dataFim.getTime() - dataInicio.getTime();
                var diffHours = diffMs / (1000 * 60 * 60);
                var precoPorHora = parseFloat("{{ campo.preco_por_hora }}");
                var precoTotal = diffHours * precoPorHora;
                document.querySelector('#preco_valor').textContent = precoTotal.toFixed(2);
                document.getElementById('preco_total').setAttribute('value', precoTotal.toFixed(2));
            } else {
                document.querySelector('#preco_valor').textContent = '0';
            }
        }

        var erroMensagem = "{{ erro_mensagem|escapejs }}";
        if (erroMensagem) {
            document.getElementById('erroMensagem').textContent = erroMensagem;
            $('#erroModal').modal('show');
        }
    });
    </script>
</body>

</html>

djangoapp/campos/templates/campos.html
{% block campos %}
<div class="container mt-4">
    <h1>Buscar Campos</h1>
    <!-- Search Form -->
    <form method="get" action="{% url 'campos:list_fields' %}">
        <div class="form-row">
            <div class="form-group col-md-3">
                <label for="id_cidade">Cidade</label>
                <input type="text" id="id_cidade" name="cidade" class="form-control" placeholder="Cidade">
            </div>
            <div class="form-group col-md-3">
                 <label for="id_tipo_gramado">Tipo de Gramado</label>
                <select id="id_tipo_gramado" name="tipo_gramado" class="form-control">
                    <option value="">Escolha...</option>
                    <option value="natural">Natural</option>
                    <option value="sintetico">Sintético</option>
                    <!-- Adicione outras opções conforme necessário -->
                </select>
            </div>
            <div class="form-group col-md-3">
                <label for="id_iluminacao_noturna">Iluminação Noturna</label>
                <select id="id_iluminacao_noturna" name="iluminacao_noturna" class="form-control">
                    <option value="">Escolha...</option>
                    <option value="true">Sim</option>
                    <option value="false">Não</option>
                </select>
            </div>
            <div class="form-group col-md-3">
                <label for="id_vestuario">Vestiário</label>
                <select id="id_vestuario" name="vestiarios" class="form-control">
                    <option value="">Escolha...</option>
                    <option value="true">Sim</option>
                    <option value="false">Não</option>
                </select>
            </div>
            <div class="form-group col-md-12">
                <button type="submit" class="btn btn-primary">Buscar</button>
            </div>
        </div>
    </form>

    <!-- Field Listings -->
    <h2 class="mt-4">Campos Disponíveis</h2>
    <div class="row">
        {% for campo in campos %}
        <div class="col-md-4">
            <div class="card field-card mb-4">
                {% if campo.foto %}
                <img src="{{ campo.foto.url }}" class="card-img-top" alt="{{ campo.nome }}">
                {% else %}
                <img src="default-field.jpg" class="card-img-top" alt="{{ campo.nome }}">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ campo.nome }}</h5>
                    <p class="card-text">Localização: {{ campo.cidade }}</p>
                    <p class="card-text">Preço: R$ {{ campo.preco_por_hora }}</p>
                    <p class="card-text">Dimensão: {{ campo.dimensao }}</p>
                    <p class="card-text">Tipo de Gramado: {{ campo.get_tipo_gramado_display }}</p>
                    <p class="card-text">Iluminação Noturna: {% if campo.iluminacao_noturna %} Sim {% else %} Não {% endif %}</p>
                    <p class="card-text">Vestiário: {% if campo.vestiarios %} Sim {% else %} Não {% endif %}</p>
                    <a href="{% url 'campos:detail_fields' campo.pk %}" class="btn btn-primary">Mais Informações</a>
                </div>
            </div>
        </div>
        {% empty %}
        <p>Nenhum campo encontrado.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}